"""
merge_fusion.py  —  Merge Myo EMG + STM32 IMU fusion captures on shared pc_t_ms.

This script merges one EMG CSV and one IMU CSV generated by capture_fusion.py
into a single synchronized CSV for downstream feature extraction and modeling.

Default behavior
----------------
- Auto-detect latest matching pair in ../emg_data:
    fusion_emg_YYYYMMDD_HHMMSS.csv
    fusion_imu_YYYYMMDD_HHMMSS.csv
- Match each EMG sample to the nearest IMU sample by pc_t_ms
- Optional max-gap guard avoids forcing poor matches at stream start/end

Usage
-----
  python merge_fusion.py
  python merge_fusion.py --timestamp 20260328_124706
  python merge_fusion.py --emg ../emg_data/fusion_emg_20260328_124706.csv \
                         --imu ../emg_data/fusion_imu_20260328_124706.csv
  python merge_fusion.py --max-gap-ms 200

Output
------
  ../emg_data/fusion_merged_YYYYMMDD_HHMMSS.csv

  Columns include:
    - Original EMG columns
    - imu_match       : 1 if nearest IMU point is within max-gap, else 0
    - imu_source_idx  : matched IMU row index (-1 when unmatched)
    - imu_pc_t_ms     : matched IMU pc_t_ms (blank when unmatched)
    - imu_dt_ms       : emg_pc_t_ms - imu_pc_t_ms (blank when unmatched)
    - imu_*           : all IMU fields (prefixed to avoid name collisions)
"""

import argparse
import csv
import glob
import os
from bisect import bisect_left

DATA_DIR = "../emg_data"
EMG_GLOB = "fusion_emg_*.csv"
IMU_GLOB = "fusion_imu_*.csv"


def parse_args():
    parser = argparse.ArgumentParser(description="Merge fusion EMG and IMU CSV files.")
    parser.add_argument("--emg", default="", help="Path to fusion_emg_*.csv")
    parser.add_argument("--imu", default="", help="Path to fusion_imu_*.csv")
    parser.add_argument(
        "--timestamp",
        default="",
        help="Timestamp suffix, e.g. 20260328_124706 (auto-builds input file names)",
    )
    parser.add_argument(
        "--out",
        default="",
        help="Output path. Default: ../emg_data/fusion_merged_<timestamp>.csv",
    )
    parser.add_argument(
        "--max-gap-ms",
        type=float,
        default=250.0,
        help="Reject nearest IMU match if |EMG pc_t_ms - IMU pc_t_ms| exceeds this value.",
    )
    return parser.parse_args()


def get_timestamp_from_name(path, prefix):
    name = os.path.basename(path)
    if not name.startswith(prefix) or not name.lower().endswith(".csv"):
        return ""
    return name[len(prefix):-4]


def build_paths_from_timestamp(base_dir, timestamp):
    emg = os.path.join(base_dir, f"fusion_emg_{timestamp}.csv")
    imu = os.path.join(base_dir, f"fusion_imu_{timestamp}.csv")
    return emg, imu


def find_latest_pair(base_dir):
    emg_paths = sorted(glob.glob(os.path.join(base_dir, EMG_GLOB)))
    imu_paths = sorted(glob.glob(os.path.join(base_dir, IMU_GLOB)))

    if not emg_paths or not imu_paths:
        raise FileNotFoundError(
            f"No fusion files found in {base_dir}. Need both {EMG_GLOB} and {IMU_GLOB}."
        )

    imu_by_ts = {
        get_timestamp_from_name(p, "fusion_imu_"): p
        for p in imu_paths
    }

    for emg_path in reversed(emg_paths):
        ts = get_timestamp_from_name(emg_path, "fusion_emg_")
        imu_path = imu_by_ts.get(ts, "")
        if imu_path:
            return emg_path, imu_path, ts

    raise FileNotFoundError(
        "Found EMG and IMU files, but no matching timestamp pair was found."
    )


def read_csv(path):
    with open(path, "r", newline="") as f:
        reader = csv.DictReader(f)
        if reader.fieldnames is None:
            raise ValueError(f"CSV has no header: {path}")
        rows = list(reader)
        return reader.fieldnames, rows


def parse_float(value, field_name, row_idx, path):
    try:
        return float(value)
    except Exception as exc:
        raise ValueError(
            f"Failed to parse float for field '{field_name}' at row {row_idx + 2} in {path}"
        ) from exc


def build_imu_index(imu_rows, imu_path):
    imu_times = []
    for i, row in enumerate(imu_rows):
        imu_times.append(parse_float(row["pc_t_ms"], "pc_t_ms", i, imu_path))

    # Ensure non-decreasing order (expected from capture script).
    for i in range(1, len(imu_times)):
        if imu_times[i] < imu_times[i - 1]:
            raise ValueError(f"IMU pc_t_ms is not non-decreasing in {imu_path}")

    return imu_times


def nearest_index(sorted_values, target):
    pos = bisect_left(sorted_values, target)
    if pos <= 0:
        return 0
    if pos >= len(sorted_values):
        return len(sorted_values) - 1

    left = pos - 1
    right = pos

    if abs(target - sorted_values[left]) <= abs(sorted_values[right] - target):
        return left
    return right


def resolve_inputs(args, base_dir):
    if args.emg and args.imu:
        emg_path = os.path.normpath(args.emg)
        imu_path = os.path.normpath(args.imu)
        ts = get_timestamp_from_name(emg_path, "fusion_emg_")
        return emg_path, imu_path, ts if ts else "manual"

    if args.timestamp:
        emg_path, imu_path = build_paths_from_timestamp(base_dir, args.timestamp)
        return emg_path, imu_path, args.timestamp

    return find_latest_pair(base_dir)


def ensure_exists(path, kind):
    if not os.path.exists(path):
        raise FileNotFoundError(f"{kind} file not found: {path}")


def main():
    args = parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    data_dir = os.path.normpath(os.path.join(script_dir, DATA_DIR))

    emg_path, imu_path, ts = resolve_inputs(args, data_dir)
    ensure_exists(emg_path, "EMG")
    ensure_exists(imu_path, "IMU")

    print(f"EMG in  : {emg_path}")
    print(f"IMU in  : {imu_path}")

    emg_header, emg_rows = read_csv(emg_path)
    imu_header, imu_rows = read_csv(imu_path)

    if not emg_rows:
        raise ValueError("EMG CSV has no data rows.")
    if not imu_rows:
        raise ValueError("IMU CSV has no data rows.")

    if "pc_t_ms" not in emg_header:
        raise ValueError("EMG CSV missing required column: pc_t_ms")
    if "pc_t_ms" not in imu_header:
        raise ValueError("IMU CSV missing required column: pc_t_ms")

    imu_times = build_imu_index(imu_rows, imu_path)

    imu_cols = [c for c in imu_header if c != "pc_t_ms"]
    out_header = list(emg_header) + [
        "imu_match",
        "imu_source_idx",
        "imu_pc_t_ms",
        "imu_dt_ms",
    ] + [f"imu_{c}" for c in imu_cols]

    if args.out:
        out_path = os.path.normpath(args.out)
    else:
        out_ts = ts if ts else "merged"
        out_path = os.path.join(data_dir, f"fusion_merged_{out_ts}.csv")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    matched = 0
    unmatched = 0

    with open(out_path, "w", newline="") as f_out:
        writer = csv.writer(f_out)
        writer.writerow(out_header)

        for i, emg_row in enumerate(emg_rows):
            emg_t = parse_float(emg_row["pc_t_ms"], "pc_t_ms", i, emg_path)
            idx = nearest_index(imu_times, emg_t)
            imu_row = imu_rows[idx]
            imu_t = imu_times[idx]
            dt = emg_t - imu_t
            is_match = abs(dt) <= args.max_gap_ms

            base = [emg_row[c] for c in emg_header]

            if is_match:
                matched += 1
                imu_values = [imu_row[c] for c in imu_cols]
                writer.writerow(base + [1, idx, f"{imu_t:.3f}", f"{dt:.3f}"] + imu_values)
            else:
                unmatched += 1
                writer.writerow(base + [0, -1, "", ""] + [""] * len(imu_cols))

    total = matched + unmatched
    print("-" * 60)
    print(f"Output  : {out_path}")
    print(f"Rows    : {total}")
    print(f"Matched : {matched}")
    print(f"Dropped : {unmatched}  (|dt| > {args.max_gap_ms} ms)")
    if total > 0:
        ratio = 100.0 * matched / total
        print(f"Coverage: {ratio:.2f}%")


if __name__ == "__main__":
    main()
