/**
 * @file config_cal.h
 * @brief Calibration data: accelerometer bias offsets, sensor-to-body axis
 *        remapping, and magnetometer hard/soft-iron correction (GY-91 only).
 *
 * Included automatically by app_config.h — do not include directly.
 */
#ifndef APP_CONFIG_CAL_H
#define APP_CONFIG_CAL_H

/* ====== ACCELEROMETER BIAS CALIBRATION ======
 * Measured per-axis zero-g offsets in raw LSB.
 * At flat rest the true Z reading is +1g; we subtract the actual +1g LSB value
 * internally, leaving just the raw offset which is subtracted here.
 *
 * To re-derive: place board FLAT AND STILL, then run via CLI:
 *   MPU CAL ACCEL 3000
 */
#if ROBOT_MODE == ROBOT_MODE_LEG
/* LEG MODE: IMU0 = ±4g (8192 LSB/g), IMU1 = ±8g (4096 LSB/g) */
#define ACCEL_BIAS_X_0 (-65)
#define ACCEL_BIAS_Y_0 (-2)
#define ACCEL_BIAS_Z_0 (219)

#define ACCEL_BIAS_X_1 (354)
#define ACCEL_BIAS_Y_1 (99)
#define ACCEL_BIAS_Z_1 (-236)

#else
/* ARM MODE: Both IMUs at ±8g (4096 LSB/g) */
#define ACCEL_BIAS_X_0 (-36)
#define ACCEL_BIAS_Y_0 (0)
#define ACCEL_BIAS_Z_0 (112)

#define ACCEL_BIAS_X_1 (361)
#define ACCEL_BIAS_Y_1 (109)
#define ACCEL_BIAS_Z_1 (-236)
#endif

/* ====== SENSOR → BODY AXIS REMAPPING ======
 * Derived from 3-pose calibration on the current board mounting.
 * To change the physical orientation, edit ONLY these six macros.
 *
 *  Inputs  : ax_s, ay_s, az_s  — sensor-frame accel  (g)
 *            wx_s, wy_s, wz_s  — sensor-frame gyro   (rad/s)
 *  Outputs : ax_g, ay_g, az_g  — body-frame  accel   (g)
 *            wx,   wy,   wz    — body-frame  gyro    (rad/s)
 */
#define REMAP_AX_G(ax_s, ay_s, az_s) ((ax_s))
#define REMAP_AY_G(ax_s, ay_s, az_s) ((ay_s))
#define REMAP_AZ_G(ax_s, ay_s, az_s) ((az_s))

#define REMAP_WX(wx_s, wy_s, wz_s) ((wx_s))
#define REMAP_WY(wx_s, wy_s, wz_s) ((wy_s))
#define REMAP_WZ(wx_s, wy_s, wz_s) ((wz_s))

/* ====== AK8963 → BODY AXIS REMAP (active when SENSOR_GY91 = 1) ======
 * The AK8963 die is physically rotated inside the MPU-9255 package:
 *   AK8963 +X ≡ accel/gyro +Y   (swap X↔Y)
 *   AK8963 +Y ≡ accel/gyro +X   (swap X↔Y)
 *   AK8963 +Z ≡ accel/gyro -Z   (negate Z)
 */
#define REMAP_MX(mx_s, my_s, mz_s) (+(my_s))
#define REMAP_MY(mx_s, my_s, mz_s) (+(mx_s))
#define REMAP_MZ(mx_s, my_s, mz_s) (-(mz_s))

/* Scale factor: 0.15 µT per LSB in 16-bit mode (AK8963 datasheet Table 3) */
#define AK8963_UT_PER_LSB 0.15f

/* ====== MAGNETOMETER CALIBRATION (active when SENSOR_GY91 = 1) ======
 * Generated by scripts/capture_mag_cal.py — paste the printed block here.
 * Online formula: m_cal = S × (m_body − b)
 */
#define MAG_CAL_BX   10.8608f
#define MAG_CAL_BY   -6.4249f
#define MAG_CAL_BZ   35.0075f

#define MAG_CAL_S11  1.1278f
#define MAG_CAL_S12  0.0452f
#define MAG_CAL_S13  0.0391f
#define MAG_CAL_S21  0.0452f
#define MAG_CAL_S22  1.0887f
#define MAG_CAL_S23 -0.0243f
#define MAG_CAL_S31  0.0391f
#define MAG_CAL_S32 -0.0243f
#define MAG_CAL_S33  0.9704f

#endif /* APP_CONFIG_CAL_H */
